### ISSUE TITLE
Create User Authentication/Accounts 

### ISSUE THREAD

**Issue by romanova2** [ucsb-cs48-w19/5pm-ucsb-rideshare#10]
This seems like it could be a good starting point: [https://scotch.io/tutorials/build-and-understand-a-simple-nodejs-website-with-user-authentication](url)

**Comment by SihuaMa12** [comment]
#46

**Comment by SihuaMa12** [comment]
https://github.com/ucsb-cs48-w19/5pm-ucsb-rideshare/tree/oauth
