### ISSUE TITLE
hello world sasha

### ISSUE THREAD

**Issue by romanova2** [ucsb-cs48-w19/5pm-ucsb-rideshare#15]
- Created a Hello,World version using the first part of the tutorial at: https://scotch.io/tutorials/build-and-understand-a-simple-nodejs-website-with-user-authentication
- located in hello_sasha directory
- Pull Request #13 hello world version of application

**Comment by pconrad** [comment]
@romanova2 Please add a link to the pull request for this issue, assign yourself another issue to work on, and drag that issue into the in-progress column. :-)
