### ISSUE TITLE
Add navbar to view layout

### ISSUE THREAD

**Issue by SamuelDunn** [ucsb-cs48-w19/5pm-ucsb-rideshare#30]
Could use Bootstrap.

**Comment by scottpchow23** [comment]
This issue needs more precision in its declaration. What should be available on the nav bar? Should any of it work? What pages do the buttons go to if they are there?

**Comment by SamuelDunn** [comment]
Nav bar will have a home button that navigates to the home page, an add ride button that will navigate to the add rides page, and a rides button that will navigate to a page where a list of available rides will be displayed. All buttons will work properly.
