### ISSUE TITLE
Allow users to filter rides based on keywords such as destination and starting point

### ISSUE THREAD

**Issue by brandonkatz** [ucsb-cs48-w19/5pm-ucsb-rideshare#53]
Option to search by price: List will be sorted cheapest price first and all prices lower than or equal to input price will be shown

Option to sort by date: List will be sorted earliest date first with all dates before or equal to input date shown

Option to search by destination: User will first enter a general area selected from a list. Then user will type in a city.

**Comment by romanova2** [comment]
filters to add
- [ ] date
- [ ] price
- [ ] time
